name: flowfit_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  page_transition: "^2.1.0"
  google_nav_bar: ^5.0.6
  flutter_svg: ^0.22.0
  showcaseview: ^2.0.3
  http: ^1.2.1
  mobile_scanner: ^4.0.0
  shared_preferences: ^2.2.2
  flutter_stripe: ^10.0.0





dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/jpg/
    - assets/jpeg/
    - assets/example.gif
    - assets/profile_example.jpg
