name: flowfit_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  page_transition: "^2.1.0"
  google_nav_bar: ^5.0.6
  flutter_svg: ^2.0.10+1
  showcaseview: ^2.0.3
  http: ^1.2.1
  mobile_scanner: ^4.0.0
  shared_preferences: ^2.2.2
  flutter_stripe: ^10.0.0
  image_picker: ^1.0.7
  dio: ^5.4.2+1





dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/png/LogoAPP.png"
  min_sdk_version: 21

flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/png/
    - assets/jpg/
    - assets/jpeg/
    - assets/example.gif
    - assets/profile_example.jpg
